### PR TITLE
Request to join the creators team

### PR DESCRIPTION
**Pull request by michielbdejong**
I would love to join [your team](https://github.com/solid/process#solidprojectorg-website). I look forward to contributing to improve and maintain the content of our project's main website, [solidproject.org](https://solidproject.org).

### CODE REVIEW

**Comment by jeff-zucker** [comment]
LGTM, I will make sure this is voted on in next team meeting.  Please add yourself to https://github.com/solid/process/issues/314.

**Comment by michielbdejong** [comment]
@jeff-zucker done! Thanks.
When is the next team meeting, should I join that one already?

**Comment by michielbdejong** [comment]
Great, thanks a lot!

**Comment by michielbdejong** [comment]
Hi @jeff-zucker 

> we discuss in the Solid Team meeting, next one tomorrow. 

Thanks! What was the outcome?

> With Timea's PR you should be on the team

Sorry, which PR was this?

**Comment by timea-solid** [comment]
Hei, thank you for being interested to be a Solid Creator. I am happy to see that part of the creators are welcoming you. 
I would like to discuss your membership in the monthly Solid Team meetings, which are every 2nd Wednesday of the month (next is on the 12th April from 14:30 UTC). With a discussion at the meeting, everyone is informed and everyone can vote (just a formality).
I think the PR Jeff was talking about was not actually a PR but you being added to the Solid Team channel on Gitter (which already happened).
As a System operator, you should be on the solid admin channel and you are invited to the monthly meetings.

**Pull request merged**
