### PR TITLE
Remove client-side libs panel

### PR DESCRIPTION
**Pull request by RubenVerborgh**
It's not really a thing.

### CODE REVIEW

**Comment by jeff-zucker** [comment]
@Mitzi-Laszlo - you merged this?  Before I even get a chance to respond to the suggestion to remove that was posted while I was asleep and acted on before I got up?  One reason I believe that this should not be removed is the question of repos - currently tools are scattered everywhere, isn't there an advantage to having them in one repo?  I would also like to hear from some of the other tool developers before closing this as a panel - @0tto_aa, @bourgeoa, @noeldmartin, @jucole who posted in the forum just yesterday that he thought this panel was a good idea.   I would also like to hear what the reason for the panel was to begin with and why those reasons no longer apply.  Is it because there has been no action so far?  It's August and many people, including me, are temporarily away or otherwise occupied.

**Comment by jeff-zucker** [comment]
Another reason I believe it is important to have a panel on libraries is that choosing libraries is a critical for app developers and rather than each library developer saying "use mine, use mine" it makes more sense to have a coordinated approach listing the strengths and weaknesses of the various tools.

**Comment by RubenVerborgh** [comment]
> I would also like to hear what the reason for the panel was to begin with

My impression was that it had emerged from a misunderstanding, namely me trying to organize the repositories at https://github.com/solid/information/blob/master/repo-overview.md by tagging leftovers with "client-side library". That seemed to have been understood as me proposing a client-side library panel.

There is definitely a need for organizing the repositories we have, but that might be broader than just client-side libs.

So good idea, and my suggestion for closing this panel was not related to that.

**Comment by jeff-zucker** [comment]
Thanks for the explanation.  I think that combining "leftovers" with client-side libraries is part of the problem.  I believe we want to encourage app developers to use standard libraries where possible and the only way to do that is by being clear what libraries are available and what the differences are between them are.  As a library developer, I'm always unsure whether my projects are useful in a bigger picture or just distractions and I could use the guidance of people like @RubenVerborgh and the other developers.  I also believe that there are many spots where we would want multiple libraries to work e.g. multiple kinds of fetch libraries or apps that can take either rdflib or comunica as parsers.   To get those kinds of plug-and-play scenarios takes coordination among projects and this seems like the place that coordination should happen.

**Comment by jeff-zucker** [comment]
OTOH, if these things are better discussed elsewhere, I'm open to that too.

**Comment by JordanShurmer** [comment]
I'm not sure a "panel" would be appropriate for this group of people discussing client side libraries, but I am def interested in discussions/plans/etc. around that topic.

I think the "panels" are meant to be more official and focused around document proposal sort of work though.

**Comment by jeff-zucker** [comment]
Good point about documentation, @JordanShurmer.  I think an "intro to Solid tools and libraries" is a much needed documentation piece.  I've made some starts at it but it is hard to even know what all the tools are and how they relate so it should be a group project.   Seems to me that the questions are unique to tools and distinct from a more general apps panel.

**Comment by Julian-Cole** [comment]
The main reason why I posted in the forum that I thought it was a good idea was because I was hoping that a panel, either in the formal or informal sense would recon / plan / prioritise / avoid lib duplication of the most needed libraries,  and also for the other reasons @jeff-zucker  puts forward.   
 And Jeff your work on your libraries is spot-on!

**Comment by Vinnl** [comment]
> Another reason I believe it is important to have a panel on libraries is that choosing libraries is a critical for app developers

I think it's a good idea for library authors to coordinate. When it comes to helping app developers pick, however, that might be more relevant to/require alignment with the Teaching Material Panel?

**Pull request merged**
